import { Texture, Color3 } from "@babylonjs/core";
export const defaultBuilding = [
  {
    type: "door",
    prop: {
      width: 4,
      height: 3,
      depth: 0.1,
      isVisible: true,
      alpha: 0.7,
      tx: new Texture(
        "https://images.pexels.com/photos/459277/pexels-photo-459277.jpeg?cs=srgb&dl=pexels-pixabay-459277.jpg&fm=jpg"
      ),
    },
    coord: [[-8, 0, 0]],
  },
  {
    type: "joint",
    prop: { width: 1, height: 1, depth: 1, isVisible: false },
    coord: [[8, 7, 0]],
  },
  {
    type: "entrance",
    prop: [
      {
        k: 1,
        width: 4,
        height: 5,
        depth: 0.1,
        rtx: 0,
        rty: 0,
        rtz: 0,
        alpha: 0.7,
        dt: false,
        dc: new Color3(0, 0, 0),
      },
      {
        k: 2,
        width: 4,
        height: 5,
        depth: 0.1,
        rtx: 0,
        rty: 0,
        rtz: 0,
        alpha: 0.7,
        dt: false,
        dc: new Color3(0, 0, 0),
      },
      {
        k: 3,
        width: 8,
        height: 1,
        depth: 0.1,
        rtx: 0,
        rty: 0,
        rtz: 0,
        alpha: 0.7,
        dt: false,
        dc: new Color3(0, 0, 0),
      },
      {
        k: 4,
        width: 4,
        height: 5,
        depth: 0.1,
        rtx: 0,
        rty: 0,
        rtz: 0,
        alpha: 1,
        dt: false,
        dc: new Color3(0, 0, 0),
      },
      {
        k: 5,
        width: 4,
        height: 5,
        depth: 0.1,
        rtx: 0,
        rty: 0,
        rtz: 0,
        alpha: 1,
        dt: false,
        dc: new Color3(0, 0, 0),
      },
    ],
    coord: [
      [-6, 2.5, 0],
      [6, 2.5, 0],
      [0, 4.5, 0],
      [-10, 2.5, 0],
      [10, 2.5, 0],
    ],
  },
  {
    type: "room",
    prop: [
      {
        k: 61,
        width: 10,
        height: 5,
        depth: 0.1,
        rtx: 0,
        rty: Math.PI / 2,
        rtz: 0,
        alpha: 1,
        dt: true,
        tx: "https://images.pexels.com/photos/479453/pexels-photo-479453.jpeg?cs=srgb&dl=pexels-iconcom-479453.jpg&fm=jpg",
      },
      {
        k: 62,
        width: 10,
        height: 5,
        depth: 0.1,
        rtx: 0,
        rty: Math.PI / 2,
        rtz: 0,
        alpha: 1,
        dt: true,
        tx: "https://images.pexels.com/photos/479453/pexels-photo-479453.jpeg?cs=srgb&dl=pexels-iconcom-479453.jpg&fm=jpg",
      },
      {
        k: 63,
        width: 5,
        height: 2.5,
        depth: 0.1,
        rtx: 0,
        rty: Math.PI / 2,
        rtz: 0,
        alpha: 0.15,
        dt: false,
        dc: new Color3(0, 0.5, 1),
      },
      {
        k: 64,
        width: 5,
        height: 2.5,
        depth: 0.1,
        rtx: 0,
        rty: Math.PI / 2,
        rtz: 0,
        alpha: 0.15,
        dt: false,
        dc: new Color3(0, 0.5, 1),
      },
      {
        k: 71,
        width: 10,
        height: 5,
        depth: 0.1,
        rtx: 0,
        rty: Math.PI / 2,
        rtz: 0,
        alpha: 1,
        dt: true,
        tx: "https://images.pexels.com/photos/479453/pexels-photo-479453.jpeg?cs=srgb&dl=pexels-iconcom-479453.jpg&fm=jpg",
      },
      {
        k: 72,
        width: 10,
        height: 5,
        depth: 0.1,
        rtx: 0,
        rty: Math.PI / 2,
        rtz: 0,
        alpha: 1,
        dt: true,
        tx: "https://images.pexels.com/photos/479453/pexels-photo-479453.jpeg?cs=srgb&dl=pexels-iconcom-479453.jpg&fm=jpg",
      },
      {
        k: 73,
        width: 5,
        height: 2.5,
        depth: 0.1,
        rtx: 0,
        rty: Math.PI / 2,
        rtz: 0,
        alpha: 0.15,
        dt: false,
        dc: new Color3(1, 1, 1),
      },
      {
        k: 74,
        width: 5,
        height: 2.5,
        depth: 0.1,
        rtx: 0,
        rty: Math.PI / 2,
        rtz: 0,
        alpha: 0.15,
        dt: false,
        dc: new Color3(0, 0.5, 1),
      },
    ],
    coord: [
      [-12, 2.5, 20],
      [-12, 2.5, 5],
      [-12, 1.25, 12.5],
      [-12, 3.75, 12.5],
      [12, 2.5, 20],
      [12, 2.5, 5],
      [12, 3.75, 12.5],
      [12, 1.25, 12.5],
    ],
  },

  {
    type: "roof",
    prop: [
      {
        k: 11,
        width: 2.5,
        height: 10,
        depth: 0.1,
        rtx: Math.PI / 2,
        rty: 0,
        rtz: 0,
        alpha: 1,
        dt: false,
        dc: new Color3(0.7, 0.7, 0.7),
      },
      {
        k: 12,
        width: 2.5,
        height: 10,
        depth: 0.1,
        rtx: Math.PI / 2,
        rty: 0,
        rtz: 0,
        alpha: 1,
        dt: false,
        dc: new Color3(0.7, 0.7, 0.7),
      },
      {
        k: 13,
        width: 2.5,
        height: 5,
        depth: 0.1,
        rtx: Math.PI / 2,
        rty: 0,
        rtz: 0,
        alpha: 0.1,
        dt: false,
        dc: new Color3(0, 0.5, 1),
      },
      {
        k: 21,
        width: 2.5,
        height: 10,
        depth: 0.1,
        rtx: Math.PI / 2,
        rty: 0,
        rtz: 0,
        alpha: 1,
        dt: false,
        dc: new Color3(0.7, 0.7, 0.7),
      },
      {
        k: 22,
        width: 2.5,
        height: 10,
        depth: 0.1,
        rtx: Math.PI / 2,
        rty: 0,
        rtz: 0,
        alpha: 1,
        dt: false,
        dc: new Color3(0.7, 0.7, 0.7),
      },
      {
        k: 23,
        width: 2.5,
        height: 5,
        depth: 0.1,
        rtx: Math.PI / 2,
        rty: 0,
        rtz: 0,
        alpha: 0.1,
        dt: false,
        dc: new Color3(0, 0.5, 1),
      },
      {
        k: 3,
        width: 19,
        height: 2.5,
        depth: 0.1,
        rtx: Math.PI / 2,
        rty: 0,
        rtz: 0,
        alpha: 1,
        dt: false,
        dc: new Color3(0.7, 0.7, 0.7),
      },
      {
        k: 4,
        width: 19,
        height: 2.5,
        depth: 0.1,
        rtx: Math.PI / 2,
        rty: 0,
        rtz: 0,
        alpha: 1,
        dt: false,
        dc: new Color3(0.7, 0.7, 0.7),
      },
      {
        k: 5,
        width: 10,
        height: 10,
        depth: 0.1,
        rtx: Math.PI / 2,
        rty: 0,
        rtz: 0,
        alpha: 1,
        dt: false,
        dc: new Color3(0.7, 0.7, 0.7),
      },
      {
        k: 6,
        width: 4.5,
        height: 10,
        depth: 0.1,
        rtx: Math.PI / 2,
        rty: 0,
        rtz: 0,
        alpha: 0.1,
        dt: false,
        dc: new Color3(0, 0.5, 1),
      },
      {
        k: 7,
        width: 4.5,
        height: 10,
        depth: 0.1,
        rtx: Math.PI / 2,
        rty: 0,
        rtz: 0,
        alpha: 0.1,
        dt: false,
        dc: new Color3(0, 0.5, 1),
      },
      {
        k: 8,
        width: 9.5,
        height: 5,
        depth: 0.1,
        rtx: Math.PI / 2,
        rty: 0,
        rtz: 0,
        alpha: 0.1,
        dt: false,
        dc: new Color3(0, 0.5, 1),
      },
      {
        k: 9,
        width: 9.5,
        height: 5,
        depth: 0.1,
        rtx: Math.PI / 2,
        rty: 0,
        rtz: 0,
        alpha: 0.1,
        dt: false,
        dc: new Color3(0, 0.5, 1),
      },
      {
        k: 10,
        width: 9.5,
        height: 5,
        depth: 0.1,
        rtx: Math.PI / 2,
        rty: 0,
        rtz: 0,
        alpha: 0.1,
        dt: false,
        dc: new Color3(0, 0.5, 1),
      },
      {
        k: 11,
        width: 9.5,
        height: 5,
        depth: 0.1,
        rtx: Math.PI / 2,
        rty: 0,
        rtz: 0,
        alpha: 0.1,
        dt: false,
        dc: new Color3(0, 0.5, 1),
      },
    ],
    coord: [
      [-10.75, 5, 20],
      [-10.75, 5, 5],
      [-10.75, 5, 12.5],
      [10.75, 5, 20],
      [10.75, 5, 5],
      [10.75, 5, 12.5],
      [0, 5, 23.75],
      [0, 5, 1.25],
      [0, 5, 12.5],
      [-7.25, 5, 12.5],
      [7.25, 5, 12.5],
      [4.75, 5, 5],
      [-4.75, 5, 5],
      [-4.75, 5, 20],
      [4.75, 5, 20],
    ],
  },
  {
    type: "oddWall",
    prop: [
      {
        k: 1,
        width: 20,
        height: 5,
        depth: 0.1,
        rtx: 0,
        rty: 0,
        rtz: 0,
        alpha: 1,
        dt: true,
        tx: "https://images.pexels.com/photos/3694711/pexels-photo-3694711.jpeg?cs=srgb&dl=pexels-mitchell-luo-3694711.jpg&fm=jpg",
      },
      {
        k: 2,
        width: 7.5,
        height: 5,
        depth: 0.3,
        rtx: 0,
        rty: Math.PI / 2,
        rtz: 0,
        alpha: 1,
        dt: true,
        tx: "https://images.pexels.com/photos/3694711/pexels-photo-3694711.jpeg?cs=srgb&dl=pexels-mitchell-luo-3694711.jpg&fm=jpg",
      },
    ],
    coord: [
      [2, 2.5, 25],
      [0, 2.5, 12.5],
    ],
  },
  {
    type: "floor",
    prop: [
      {
        k: 1,
        width: 24,
        height: 25,
        depth: 0.1,
        rtx: -Math.PI / 2,
        rty: 0,
        rtz: 0,
        alpha: 1,
        dt: true,
        tx: "https://images.pexels.com/photos/2117937/pexels-photo-2117937.jpeg?cs=srgb&dl=pexels-scott-webb-2117937.jpg&fm=jpg",
      },
    ],
    coord: [[0, 0, 12.5]],
  },
  {
    type: "evenWall",
    prop: [
      {
        k: 1,
        width: 20,
        height: 5,
        depth: 0.1,
        rtx: 0,
        rty: 0,
        rtz: 0,
        alpha: 1,
        dt: true,
        tx: "https://images.pexels.com/photos/3694711/pexels-photo-3694711.jpeg?cs=srgb&dl=pexels-mitchell-luo-3694711.jpg&fm=jpg",
      },
      {
        key: 2,
        width: 7.5,
        height: 5,
        depth: 1,
        rtx: 0,
        rty: 0,
        rtz: 0,
        dt: false,
        dc: new Color3(0.2, 0.2, 0.2),
      },
      {
        key: 3,
        width: 7.5,
        height: 5,
        depth: 1,
        rtx: 0,
        rty: 0,
        rtz: 0,
        dt: false,
        dc: new Color3(0.2, 0.2, 0.2),
      },
    ],
    coord: [
      [-2, 5, 20],
      [0, 5, 15],
      [0, 5, 10],
    ],
  },

  // {
  //     "type": "oddSeparator",
  //     "prop": { "width": 30, "height": 20, "depth": 1, "rtx": 0, "rty": Math.PI / 2, "rtz": 0, "dt": false, "dc": new Color3(0.2,0.2,0.2) },
  //     "coord": [[0, 10, 50]]
  // },
  // {
  //     "type": "evenSeparator",
  //     "prop": [
  //         { "key": 1, "width": 30, "height": 20, "depth": 1, "rtx": 0, "rty": 0, "rtz": 0, "dt": false, "dc": new Color3(0.2,0.2,0.2) },
  //         { "key": 2, "width": 30, "height": 20, "depth": 1, "rtx": 0, "rty": 0, "rtz": 0, "dt": false, "dc": new Color3(0.2,0.2,0.2) }

  //     ],
  //     "coord": [[0, 10, 60], [0, 10, 40]]
  // },

  // {
  //   type: "light",
  //   prop: { intensity: 0.7 },
  //   coord: [[0, 25, 20]],
  // },
];
